ams/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teacher.urls'))
]

admin.site.site_header = 'TEACHERS ADMIN'

teacher/urls.py
from django.urls import path, include
from . import views
app_name= "teacher"
urlpatterns = [
    path('signup/', views.signupTeacher, name="signup"),
    path('signin/', views.signinTeacher, name="signin"),
    path('', views.dashboard, name="dashboard"),

    path('takeattendance/<slug:code>', views.takeattendance, name="takeattendance"),
    path('takeattendance/', views.redtakeattendance, name="redtakeattendance"),

    path('history/', views.history, name="history"),
    path('history/<slug:code>', views.viewhistory, name="viewhistory"),
    path('signout/', views.signoutTeacher, name="signout")
]

teacher/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password

class TeacherManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("User must have an email address")
        if not username:
            raise ValueError("User must have a username")

        user = self.model(
            email = self.normalize_email(email),
            username = username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            password = password,
            username = username,
        )
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using = self._db)
        return user
class Teacher(AbstractBaseUser):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    email = models.EmailField(max_length = 50, unique = True)
    username = models.CharField(max_length = 20, primary_key= True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    objects = TeacherManager()

    class Meta:
        ordering = ['first_name']


    def has_perm(self, perm, obj= None):
        return self.is_active
    
    def has_module_perms(self, app_label):
        return True

    def __str__(self):
        return  self.username

class Batch(models.Model):
    semester_id = models.CharField(max_length = 20, primary_key = True, null = False)
    semester = models.CharField(max_length = 20)
    department = models.CharField(max_length = 20)

    class Meta:
        ordering = ['semester_id']
    
    def __str__(self):
        return "%s %s" % (self.department, self.semester)
    
class Course(models.Model):
    code = models.CharField(max_length = 10, primary_key = True)
    title = models.CharField(max_length = 50)
    semester = models.ForeignKey(Batch, on_delete= models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete= models.CASCADE)

    class Meta:
        ordering = ['code']

    def __str__(self):
        return self.title

class Student(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    registration_no = models.CharField(max_length = 15, primary_key = True)
    roll_no = models.CharField(max_length = 10)
    session = models.CharField(max_length = 10)
    semester = models.ForeignKey(Batch, on_delete= models.CASCADE)
    attendances = models.ManyToManyField(Course, through='Attendance')

    class Meta:
        ordering = ['first_name']

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete= models.CASCADE)
    student = models.ForeignKey(Student, on_delete= models.CASCADE)
    date = models.DateField()
    status = models.BooleanField()
    createdAt = models.DateTimeField(auto_created=True, auto_now=True)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'{self.date} - {self.course} - {self.student}'

teacher/forms.py
from datetime import date, timedelta
from django.forms import ModelForm, formset_factory
from django import forms
from .models import Teacher, Attendance

class TeacherSignUpForm(ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            'password'
        ]

class TeacherSignInForm(ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'email',
            'password'
        ]


class AttendanceForm(forms.Form):
    student_name = forms.CharField(max_length=255, required=False)
    student_id = forms.CharField(max_length=255, required=False)
    course_id = forms.CharField(max_length=255, required=False)
    roll_no = forms.CharField(max_length=10, required=False)
    status = forms.BooleanField(required=False)
    date = forms.CharField(required=False)


class AttendanceDateForm(forms.Form):
    date_choices = [(str(date.today() - timedelta(i)), (str(date.today() - timedelta(i)))) for i in range(7)]

    attendance_date = forms.ChoiceField(choices=tuple(date_choices))

    class Meta:
        fields = ["attendance_date"]

teacher/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory

from datetime import datetime

from .models import *
from .forms import AttendanceDateForm, TeacherSignUpForm, TeacherSignInForm, AttendanceForm
from .decorators import verify

@verify
def signupTeacher(request):
    if request.method == 'POST':
        form = TeacherSignUpForm(request.POST)
        if form.is_valid():
            teacher = form.save(commit=False)
            password = form.cleaned_data['password']
            teacher.set_password(password)
            teacher.save()
            messages.success(request, 'Account successfully created.')
            return redirect('teacher:signin')
        else:
            messages.error(request, 'Email or Username already taken.')
    
    form = TeacherSignUpForm()
    context = {
        'form': form,
    }
    return render(request, 'teacher/signup.html', context)

@verify
def signinTeacher(request):
    if request.method == 'POST':
        form = TeacherSignInForm(request.POST)        
        email = form['email'].value()
        password = form['password'].value()
        user = authenticate(request, username = email, password = password)
        if user is not None:
            login(request, user)
            return redirect('teacher:dashboard')
        else:
            messages.error(request, 'Incorrect email or password.')
        
    form = TeacherSignInForm()
    context = {
        'form': form
    }
    return render(request, 'teacher/signin.html', context)

def signoutTeacher(request):
    logout(request)
    return redirect('teacher:signin')

@login_required(login_url='teacher:signin')
def dashboard(request):
    today = datetime.today().strftime('%Y-%m-%d')
    assigned_course = Course.objects.filter(teacher = request.user).values()
    message = None
    if 'error_message' in request.session:
        message = request.session['error_message']
        del request.session['error_message']
        messages.error(request, message)

    context = {
        'courses': assigned_course,
        'nav': 'dashboard',
        'attendance_date': today
    }
    return render(request, 'teacher/dashboard.html', context)


@login_required(login_url='teacher:signin')
def takeattendance(request, code):
    today = request.GET.get('attendance_date', datetime.today().strftime('%Y-%m-%d'))
    # # today = datetime.today().strftime('%Y-%m-%d')
    # print(request.GET)
    course = Course.objects.filter(code=code).values()
    
    students = Student.objects.filter(semester = course[0]['semester_id']).order_by('roll_no').values()
    no_of_students = 0
    attendance_info = []

    for student in students:
        current_student_status = Attendance.objects.filter(date=today, course_id=code, student_id=student['registration_no']).order_by('-createdAt').first()
        info = {
            'student_name': student['first_name'] + ' ' +  student['last_name'],
            'course_id': course[0]['code'],
            'student_id': student['registration_no'],
            'roll_no': student['roll_no'],
            'status': current_student_status.status if current_student_status else False,
            'date': today
        }
        attendance_info.append(info)
        no_of_students += 1

    formset = formset_factory(AttendanceForm, max_num=no_of_students)
    if request.method == 'POST':
        forms = formset(request.POST)
        if forms.is_valid():
            total_student = 0
            total_present = 0
            total_absent = 0
            for form in forms:
                if form.is_valid():
                    course_id = Course.objects.get(code = form.cleaned_data['course_id'])
                    student_id = Student.objects.get(registration_no = form.cleaned_data['student_id'])
                    date = form.cleaned_data['date']
                    status = form.cleaned_data['status']
                    total_student += 1
                    
                    if status:
                        total_present += 1
                    else:
                        total_absent += 1

                    current_student_status = Attendance.objects.filter(date=today, course_id=code, student_id=student_id).order_by('-createdAt').first()
                    
                    if current_student_status:
                        attendance_model = Attendance.objects.filter(date=today, course_id=code, student_id=student_id).update(
                            course = course_id,
                            student = student_id,
                            date = date,
                            status = status
                        )
                    else: 
                        attendance_model = Attendance.objects.create(
                            course = course_id,
                            student = student_id,
                            date = date,
                            status = status
                        )
                        attendance_model.save()
            absent_percentage = ((total_student-total_present)/total_student) * 100
            present_percentage = 100 - absent_percentage
            context = {
                'total_student': total_student,
                'total_present': total_present,
                'total_absent': total_absent,
                'absent_percentage': absent_percentage,
                'present_percentage': present_percentage
            }
            return render(request, 'teacher/report.html', context)
        else:
            return HttpResponseNotFound('Error while submiting the attendance. Please try again later.')

    forms = formset(initial=attendance_info)
    
    context = {
        'forms': forms,
        'date_form': AttendanceDateForm(),
        'date': datetime.today().strftime('%Y-%m-%d'),
        'course_title': course[0]['title'], 
    }

    return render(request, 'teacher/takeattendance.html', context)


@login_required(login_url='teacher:signin')
def redtakeattendance(request):
    return redirect('teacher:dashboard')

@login_required(login_url='teacher:signin')
def history(request):
    courses = Course.objects.filter(teacher = request.user).values()
    return render(request, 'teacher/history.html', {'nav': 'history', 'courses': courses})
    
@login_required(login_url='teacher:signin')
def viewhistory(request, code):
    # Dates of attendances taken
    dates = Attendance.objects.filter(course_id=code).order_by('-date').values('date').distinct()
    # Get the details of the course using code
    course = Course.objects.filter(code=code).values()
    # Get the student list who enrolled this course
    students = Student.objects.filter(semester = course[0]['semester_id']).order_by('roll_no').values()
    student_info = []
    for student in students:
        std = {
            'name': student['first_name'] + ' ' +  student['last_name'],
            'roll_no': student['roll_no']
        }
        attendances = []
        for date in dates:
            atndance = Attendance.objects.filter(course_id = code).filter(date = date['date']).filter(student_id=student['registration_no']).values()
            attendances.append('P' if atndance[0]['status'] == True else 'A')
        std.update(
            {'attendances': attendances}
        )
        student_info.append(std)
    context = {
        'student_info': student_info,
        'dates': dates,
        'course': course[0]['title']
    }
    return render(request, 'teacher/details.html', context)

teacher/templates/teacher/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'teacher/includes/css.html' %}
    {% block title%}
    {% endblock %}
</head>

<body>
    {% block navbar%}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
        <footer class="page-footer font-small">
            <div class="footer-copyright text-center py-3">All rights reserved © 2022</div>
        </footer>
    {% endblock %}
</body>
{% include 'teacher/includes/js.html' %}

</html>

teacher/templates/teacher/dashboard.html
{% extends 'teacher/base.html' %}
{% block title %}
<title>Dashboard</title>
{% endblock%}
{% block navbar %}
{% include 'teacher/navbar.html' %}
{% endblock %}
{% block content %}
<div class="container mt-5" >
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    <h2> Assigned Courses </h2>

    {% if courses|length > 0 %}
    <div style="overflow-x: scroll;">
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>#</th>
                <th>Course Title</th>
                <th>Semester</th>
                <th>Course Code</th>
                <th>Option</th>
            </tr>
        </thead>
        {% for course in courses %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ course.title }}</td>
            <td>{{ course.semester_id }} </td>
            <td>{{ course.code }} </td>
            <td style="padding-top:5px; padding-bottom:5px;"> <a
                    class="text-decoration-none btn btn-light btn-block btn-md font-weight-bold"
                    href="{% url 'teacher:takeattendance' course.code %}?attendance_date={{attendance_date}}">Take Attendance</a> </td>
        </tr>
        {% endfor %}
    </table>
    </div>
    {% else %}
    <div class="card-body">
        <h5>No course assigned to you. Contact a course co-ordinator to assign a course.</h4>
    </div>
    {% endif %}
</div>
{% endblock %}

teacher/templates/teacher/details.html
{% extends 'teacher/base.html' %}
{% block title %}
<title>Dashboard</title>
{% endblock%}
{% block navbar %}
{% include 'teacher/navbar.html' %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <h2>Attendance Details of {{course}}</h2>
    <div style="overflow-x: scroll;">
        <table class="table table-bordered ">
            <thead class="thead-light">
                <tr>
                    <th class="frozen">Roll Number</th>
                    <th>Student Name</th>
                    {% for date in dates %}
                    <th> {{date.date}} </th>
                    {% endfor %}
                </tr>
            </thead>
            {% for info in student_info %}
            <tr>
                <th class="frozen">{{ info.roll_no }}</th>
                <td>{{ info.name }}</td>
                {% for attendance in info.attendances %}
                    {% if attendance == 'A' %}
                    <td style="color: #FF4500;; font-weight: bold;"> {{attendance}} </td>
                    {% else %}
                    <td style="color: #4bb543; font-weight: bold;"> {{attendance}}</td>
                    {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

teacher/templates/teacher/formpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'teacher/includes/css.html' %}
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
    {% block title%}
    {% endblock %}
</head>

{% block content %}
{% endblock %}

{% include 'teacher/includes/js.html' %}

</html>

teacher/templates/teacher/history.html
{% extends 'teacher/base.html' %}
{% block title %}
<title>Dashboard</title>
{% endblock%}
{% block navbar %}
{% include 'teacher/navbar.html' %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <h2>Attendance Sheet</h2>
    <div id="accordion">
        {% for course in courses %}
        <div class="card card-deck mb-4">
            <div class="card-header" id="heading{{ course.code }}">
                <h5 class="mb-0">
                    <button class="btn btn-light" data-toggle="collapse" data-target="#collapse{{ course.code }}"
                        aria-expanded="true" aria-controls="collapse{{ course.code }}">
                       {{ course.title }}
                    </button>
                </h5>
            </div>
            <div id="collapse{{ course.code }}" class="collapse" aria-labelledby="heading{{ course.code }}"
                data-parent="#accordion">
                <div class="card-body">
                    <a class="text-decoration-none btn btn-primary btn-sm font-weight-bold"
                        href="{% url 'teacher:viewhistory' course.code %}" >View All</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

teacher/templates/teacher/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand font-weight-bold" href="{% url 'teacher:dashboard' %}">AMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item {% if nav == 'dashboard' %} active {% endif %}">
                <a class="nav-link font-weight-bold" href="{% url 'teacher:dashboard' %}">DASHBOARD</a>
            </li>
            <li class="nav-item {% if nav == 'history' %} active {% endif %} ">
                <a class="nav-link font-weight-bold" href="{% url 'teacher:history' %}">HISTORY</a>
            </li>
            <li>
                <div class="dropdown" style="position:absolute; right:0;">
                    <button class="btn btn-dark dropdown-toggle nav-link" style="font-weight:bold;" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    You are signed in as: {{ request.user }}
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'teacher:signout' %}">SIGNOUT</a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>

teacher/templates/teacher/report.html
{% extends 'teacher/base.html' %}
{% block title %}
<title>Take Attendance</title>
{% endblock%}
{% block navbar %}
{% include 'teacher/navbar.html' %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <h4>Report Generated</h4>

    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>Total student</th>
                <th>Present</th>
                <th>Absent</th>
                <th>Present %</th>
                <th>Absent %</th>
            </tr>
        </thead>
        <tr>
            <td>{{total_student}}</td>
            <td>{{total_present}}</td>
            <td>{{total_absent}}</td>
            <td>{{present_percentage}}%</td>
            <td>{{absent_percentage}}%</td>
        </tr>
    </table>
    <div class="text-center">
        <a class="text-decoration-none btn btn-success btn-md font-weight-bold" href="{% url 'teacher:dashboard' %}">Go
            to Dashboard</a>
    </div>
</div>
{% endblock %}

teacher/templates/teacher/signin.html
{% extends 'teacher/formpage.html' %}

{% block title %}
<title>Signin</title>
{% endblock %}

{% block content %}

<body class='text-center'>
    {% load widget_tweaks %}
    <form class="form-signin" method="POST">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Teacher Panel</h1>
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
        {% render_field form.email class="form-control" placeholder="you@email.com" required="" autocomplete="off" type="email" %}
        {% render_field form.password class="form-control" placeholder="password" required="" autocomplete="off" type="password" %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="h6 mt-2">Don't have an account? <a class="text-decoration-none" href="{% url 'teacher:signup' %}">Sign up</a>
        </p>
        <p class="mt-5 mb-3 text-muted">© 2020-2021</p>
    </form>
</body>

{% endblock %}

teacher/templates/teacher/signup.html
{% extends 'teacher/formpage.html' %}

{% block title %}
<title>Signup</title>
{% endblock %}

{% block content %}

<body class='text-center'>
    {% load widget_tweaks %}
    <form class="form-signin" method="POST">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Teacher Sign Up</h1>
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
        {% render_field form.first_name class="form-control" placeholder="first name" required="" autocomplete="off" type="text" %}
        {% render_field form.last_name class="form-control" placeholder="last name" required="" autocomplete="off" type="text" %}
        {% render_field form.email class="form-control" placeholder="you@email.com" required="" autocomplete="off" type="email" %}
        {% render_field form.username class="form-control" placeholder="username" required="" autocomplete="off" type="text" %}
        {% render_field form.password class="form-control" placeholder="password" required="" autocomplete="off" type="password" %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
        <p class="h6 mt-2">Already have an account? <a class="text-decoration-none" href="{% url 'teacher:signin' %}">Sign
                In</a></p>
        <p class="mt-5 mb-3 text-muted">© 2020-2021</p>
    </form>
</body>
{% endblock %}

teacher/templates/teacher/takeattendance.html
{% extends 'teacher/base.html' %}
{% block title %}
<title>Take Attendance</title>
{% endblock%}
{% block navbar %}
{% include 'teacher/navbar.html' %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <h2>{{ course_title }}</h2>
    <form method="GET" style='text-transform: capitalize; margin-bottom: 1rem;'>
        {{ date_form }}
        <button class="btn btn-success font-weight-bold btn-sm" type="submit">Submit</button>
    </form>
    {% load widget_tweaks %}
    <form method="POST">
        {% csrf_token %}
        {{ forms.management_form }}
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr class="text-uppercase">
                    <th>#</th>
                    <th>Student Name</th>
                    <th>Roll No</th>
                    <th>Status</th>
                </tr>
            </thead>

            {% for form in forms %}
            <tr>
                {% render_field form.student_name hidden="" %}
                {% render_field form.course_id hidden="" %}
                {% render_field form.student_id hidden="" %}
                {% render_field form.roll_no hidden="" %}
                {% render_field form.date hidden="" %}


                <td>{{ forloop.counter }}</td>
                <td>{{ form.student_name.value }}</td>
                <td>{{ form.roll_no.value }} </td>
                <td>
                    {% render_field form.status type="checkbox" class="switch" %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class="text-center">
            <button class="btn btn-success font-weight-bold btn-md" type="submit">Submit</button>
        </div>
    </form>

</div>

<script>
    const dateSelect = document.querySelector('#id_attendance_date')
    const attendance_date = window.location.search.split('?attendance_date=')[1]

    dateSelect.value = attendance_date
    dateSelect.style.padding = '.15rem'
</script>
{% endblock %}